# Generated by Django 3.2.9 on 2023-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='user_prompt',
            field=models.JSONField(default='[]'),
        ),
    ]
