# Generated by Django 3.2.9 on 2023-04-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprompt_user_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='user_prompt',
            field=models.JSONField(default=list),
        ),
    ]
